site:
  datasource_driver: com.mysql.cj.jdbc.Driver
  datasource_url: jdbc:mysql://mysql:3306/pybbs?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  datasource_username: root
  datasource_password: dangerous # 这个密码跟 docker-compose.yml 里的 MYSQL_ROOT_PASSWORD 密码是一样的，不能为空

server:
  port: 8088
  servlet:
    context-path:
      /kaopu
